package com.example.homex.app

const val EMAIL = "EMAIL"
const val POPUP_MODEL = "popup_model"
const val HOME = "HOME"
const val SUGGEST = "SUGGEST"
const val CHAT_HUB_URL = "https://gcsoft.dev/ChatHub"
const val RECEIVE_MESSAGE = "ReceiveMessages"
const val ID = "ID"
const val CONNECT_CHAT = "CONNECT_CHAT"
const val CONTACT_USER = "CONTACT_USER"
const val USER_ACCESS = "USER_ACCESS"
const val REQUEST_STATUS = "REQUEST_STATUS"
const val NOTIFICATIONS = "Notification"
const val IMAGE = "IMAGE"
const val DATE_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
const val CITY = "CITY"
const val DISTRICT = "DISTRICT"
const val PEOPLE = "PEOPLE"
const val START_DATE = "START_DATE"
const val END_DATE = "END_DATE"
const val CITY_NAME = "CITY_NAME"
const val DISTRICT_NAME = "DISTRICT_NAME"
const val LOCATION = "LOCATION"
const val FILTER = "FILTER"
const val PAYMENT_STATUS = "PAYMENT_STATUS"